export enum EntityName {
    Otp = "otp",
    User = 'user',
    Station = 'station',
    AvgSale = 'average-sale',
    Inventory = 'inventory',
    Capacity = 'capacity',
    Location = 'location',
    Notification = 'notification',
    Depot = 'depot',
    Tanker = 'tanker',
    Request = 'request',
    Cargo = 'cargo',
    Ticket = "ticket",
    Status = "status",
    FuelType = "fuel-type",
    Reject = "reject",
    Plate = "plate",
    Limit = "limit",
}